2016-08-18 16:38:41,083 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 16:38:41,084 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Not Found']
2016-08-18 16:38:41,084 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 16:38:41,084 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 16:38:41,084 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 16:38:41,096 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 16:38:41,096 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 16:38:41,097 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 1.0
 *       Run Number: 20160818163841-4
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818163841-4.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=shiftroster;Version=1.0;JobID=20160818163841-4;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818163841-4.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 16:38:41,097 - teradata.udaexec - INFO - Creating connection: {'username': 'select_user', 'password': 'XXXXXX', 'system': 'tiescfm01', 'method': 'odbc'}
2016-08-18 16:38:41,174 - teradata.udaexec - INFO - Connection successful. Duration: 0.076 seconds. Details: {'username': 'select_user', 'password': 'XXXXXX', 'system': 'tiescfm01', 'method': 'odbc'}
2016-08-18 16:38:41,181 - teradata.udaexec - INFO - Query Successful. Duration: 0.007 seconds, Rows: 1, Query: select * from trm.employee_detail where e_empid=10316
2016-08-18 16:39:30,752 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-18 16:39:30,752 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2016-08-18 16:39:30,763 - teradata.udaexec - INFO - UdaExec exiting.
