2016-08-18 17:26:40,768 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:26:40,768 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:26:40,768 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:26:40,768 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:26:40,768 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:26:40,799 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:26:40,800 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:26:40,800 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818172640-10
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818172640-10.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818172640-10;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818172640-10.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:26:40,801 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:26:43,395 - teradata.udaexec - INFO - Connection successful. Duration: 2.832 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:26:43,432 - teradata.udaexec - INFO - Query Successful. Duration: 0.037 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:26:43,471 - teradata.udaexec - INFO - Connection successful. Duration: 2.670 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:26:43,493 - teradata.udaexec - INFO - Query Successful. Duration: 0.022 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:26:49,361 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:26:49,361 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:26:49,361 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:26:49,361 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:26:49,362 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:26:49,371 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:26:49,371 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:26:49,372 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818172649-11
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818172649-11.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818172649-11;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818172649-11.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:26:49,373 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:26:49,470 - teradata.udaexec - INFO - Connection successful. Duration: 0.097 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:26:49,492 - teradata.udaexec - INFO - Query Successful. Duration: 0.022 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:47:26,458 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:47:26,459 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:47:26,459 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:47:26,459 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:47:26,460 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:47:26,480 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:47:26,481 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:47:26,481 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818174726-12
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818174726-12.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818174726-12;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818174726-12.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:47:26,482 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:47:26,589 - teradata.udaexec - INFO - Connection successful. Duration: 0.106 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:47:26,596 - teradata.udaexec - INFO - Query Successful. Duration: 0.006 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:47:27,227 - django.request - WARNING - Not Found: /favicon.ico
2016-08-18 17:47:30,366 - django.request - WARNING - Not Found: /shiftroster/wfhform.html
2016-08-18 17:50:37,991 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:50:37,991 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:50:37,991 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:50:37,992 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:50:37,992 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:50:38,011 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:50:38,011 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:50:38,012 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818175037-13
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175037-13.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818175037-13;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175037-13.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:50:38,013 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:50:38,096 - teradata.udaexec - INFO - Connection successful. Duration: 0.082 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:50:38,103 - teradata.udaexec - INFO - Query Successful. Duration: 0.006 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:50:40,001 - django.request - WARNING - Not Found: /shiftroster/wfhform.html
2016-08-18 17:50:45,263 - django.request - WARNING - Not Found: /shiftroster/tcrform.html
2016-08-18 17:50:46,376 - django.request - WARNING - Not Found: /shiftroster/wfhform.html
2016-08-18 17:51:03,279 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:51:03,279 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:51:03,279 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:51:03,280 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:51:03,280 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:51:03,315 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:51:03,316 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:51:03,316 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818175103-14
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175103-14.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818175103-14;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175103-14.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:51:03,319 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:03,348 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:51:03,349 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:51:03,349 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:51:03,350 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:51:03,350 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:51:03,371 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:51:03,372 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:51:03,372 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818175103-15
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175103-15.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818175103-15;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175103-15.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:51:03,374 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:03,438 - teradata.udaexec - INFO - Connection successful. Duration: 0.118 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:03,446 - teradata.udaexec - INFO - Query Successful. Duration: 0.007 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:51:03,515 - teradata.udaexec - INFO - Connection successful. Duration: 0.140 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:03,538 - teradata.udaexec - INFO - Query Successful. Duration: 0.022 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:51:04,733 - django.request - WARNING - Not Found: /wfh
2016-08-18 17:51:32,715 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:51:32,715 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:51:32,716 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:51:32,716 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:51:32,717 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:51:32,728 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:51:32,729 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:51:32,729 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818175132-16
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175132-16.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818175132-16;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175132-16.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:51:32,731 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:32,805 - teradata.udaexec - INFO - Connection successful. Duration: 0.073 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:32,812 - teradata.udaexec - INFO - Query Successful. Duration: 0.007 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:51:34,508 - django.request - WARNING - Not Found: /wfh
2016-08-18 17:51:45,560 - teradata.udaexec - INFO - Initializing UdaExec...
2016-08-18 17:51:45,561 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
2016-08-18 17:51:45,561 - teradata.udaexec - INFO - Found run number file: "C:\Users\BS255029\Documents\Shift\Shift\mysite\.runNumber"
2016-08-18 17:51:45,562 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-08-18 17:51:45,562 - teradata.udaexec - INFO - Removed 0 log files.
2016-08-18 17:51:45,573 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\BS255029\Documents\Shift\Shift\mysite\shiftroster.checkpoint
2016-08-18 17:51:45,574 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-08-18 17:51:45,574 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: shiftroster
 *          Version: 2
 *       Run Number: 20160818175145-17
 *             Host: WINBS255029-O9Y
 *         Platform: Windows-7-6.1.7601-SP1
 *          OS User: bs255029
 *   Python Version: 3.4.4
 *  Python Compiler: MSC v.1600 64 bit (AMD64)
 *     Python Build: ('v3.4.4:737efcadf5a6', 'Dec 20 2015 20:20:57')
 *  UdaExec Version: 15.10.0.17
 *     Program Name: manage.py
 *      Working Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite
 *          Log Dir: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs
 *         Log File: C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175145-17.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\udaexec.ini: Not Found', 'C:\\Users\\BS255029\\Documents\\Shift\\Shift\\mysite\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=shiftroster;Version=2;JobID=20160818175145-17;ClientUser=bs255029;Production=False;udaAppLogFile=C:\Users\BS255029\Documents\Shift\Shift\mysite\logs\shiftroster.20160818175145-17.log;UtilityName=PyTd;UtilityVersion=15.10.0.17
********************************************************************************/
2016-08-18 17:51:45,577 - teradata.udaexec - INFO - Creating connection: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:45,675 - teradata.udaexec - INFO - Connection successful. Duration: 0.098 seconds. Details: {'charset': 'UTF8', 'username': 'select_user', 'externalDSN': 'TIES', 'method': 'odbc', 'password': 'XXXXXX', 'system': 'tiescfm01'}
2016-08-18 17:51:45,682 - teradata.udaexec - INFO - Query Successful. Duration: 0.006 seconds, Rows: 2, Query: select * from trm.employee_detail where e_empid=10316 or e_empid=10317
2016-08-18 17:51:46,754 - django.request - WARNING - Not Found: /shiftroster/wfhform.html
2016-08-18 17:51:47,940 - django.request - WARNING - Not Found: /shiftroster/tcrform.html
2016-08-19 10:02:18,802 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,127 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,128 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,129 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,129 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,130 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,130 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,131 - teradata.udaexec - INFO - UdaExec exiting.
2016-08-19 10:02:19,337 - teradata.udaexec - INFO - UdaExec exiting.
